"""Auto-generate PLAN.md (problem + data + method) and RESULTS.md (findings).

Both documents are regenerated after every loop run from the latest iteration's
state. They are written as final-product narrative documents — they describe
the current best understanding, not the iteration trail. Iteration-by-iteration
details live in `state/iter_log.jsonl` and `state/iter_NNN/`.

Do not hand-edit PLAN.md or RESULTS.md — your edits will be overwritten on
the next loop run. To preserve a hand-written version, save under a different
filename.
"""

from __future__ import annotations
import json
from pathlib import Path
from collections import Counter
from .core import STATE

ROOT = Path(__file__).resolve().parents[1]
PLAN_MD = ROOT / "PLAN.md"
RESULTS_MD = ROOT / "RESULTS.md"

AUTO_HEADER = (
    "<!-- Auto-generated by `python -m pipeline.loop`. Reflects the current "
    "best analysis. Do not hand-edit; regenerated each loop run. -->\n\n"
)

# Domain-knowledge metadata used to describe sources in human terms
SOURCE_DESCRIPTIONS = {
    "ximerakis_cellchat": ("Ximerakis 2023 *Nat Aging* Suppl. Table 20",
                           "CellChat ligand–receptor pairs active in each of the 6 parabiosis "
                           "conditions (YY/YX/OY/YO/OX/OO); we use it to define the receptor "
                           "universe — only receptors whose signaling is condition-dependent qualify"),
    "ximerakis_tpms":     ("Ximerakis 2023 *Nat Aging* Suppl. Table 6",
                           "Per-cell-type TPMs for all 6 parabiosis conditions; lets us compute "
                           "Spearman dose-response of each receptor against the blood-age axis"),
    "lehallier_st1":      ("Lehallier 2019 *Nat Med* Suppl. Table 1",
                           "Maps SomaScan reagent IDs to gene symbols — required to join plasma "
                           "data to the OmniPath ligand–receptor catalog"),
    "lehallier_st4":      ("Lehallier 2019 *Nat Med* Suppl. Table 4",
                           "Per-protein age coefficient + q-value across n=4,263 humans (18–95y); "
                           "the primary plasma age signal"),
    "lehallier_st14":     ("Lehallier 2019 *Nat Med* Suppl. Table 14",
                           "DE-SWAN three-decade structure (4th, 7th, 8th decade waves); we "
                           "weight 7th-decade ligands more heavily because that window aligns "
                           "with onset of cognitive decline"),
    "jeffries_s7":        ("Jeffries 2025 *Nature* Suppl. Table 7",
                           "Per-cell-type continuous age slope in human PFC across the full "
                           "lifespan; used to test cross-species replication"),
    "omnipath":           ("OmniPath ligand–receptor catalog",
                           "Curated union of CellPhoneDB, CellTalkDB, Cellinker, Baccin2019, "
                           "Guide2Pharma, Ramilowski2015, etc. — provides ligand↔receptor edges "
                           "and agonist/antagonist annotations"),
    "palovics":           ("Pálovics 2022 *Nature* brain subset (Figshare 119145)",
                           "Independent mouse parabiosis cohort, used only to replicate the "
                           "short list once a top hit emerges"),
}

BBB_FACING = {"EC", "PC", "VSMC", "MG", "MNC", "DC", "ABC", "VLMC", "CPC"}

# Known receptor families for system-level pattern detection
RECEPTOR_FAMILIES = {
    "FZD":  "Wnt/Frizzled receptor family",
    "BMPR": "BMP receptor family",
    "ACVR": "Activin/BMP receptor family",
    "TGFBR": "TGF-β receptor family",
    "FGFR": "FGF receptor family",
    "IGF":  "Insulin-like growth factor receptor",
    "VEGFR": "VEGF receptor family",
    "FLT":  "VEGF receptor family",  # FLT1 = VEGFR1
    "KDR":  "VEGF receptor family",  # KDR = VEGFR2
    "NRP":  "Neuropilin (VEGF co-receptor) family",
    "CXCR": "CXC chemokine receptor family",
    "CCR":  "CC chemokine receptor family",
    "ITGA": "Integrin alpha family",
    "ITGB": "Integrin beta family",
    "TLR":  "Toll-like receptor family",
    "TNFRSF": "TNF receptor superfamily",
    "NOTCH": "Notch receptor family",
    "ADGR": "Adhesion GPCR family",
    "LRP":  "LDL receptor-related protein family (Wnt co-receptor)",
}

POSITIVE_CONTROLS = {  # known brain-aging-relevant receptors for sanity check
    "LRP6": "Wnt co-receptor; SOST/DKK1 axis",
    "CD44": "hyaluronan receptor; senescence marker",
    "CXCR4": "SDF-1 receptor; neurogenesis",
    "C3AR1": "complement receptor; neuroinflammation",
    "C5AR1": "complement receptor; neuroinflammation",
    "IL6ST": "gp130; IL-6 family neuroinflammation",
    "TGFBR1": "TGF-β receptor",
    "TGFBR2": "TGF-β receptor",
    "BMPR1A": "BMP receptor; GDF11 axis",
    "BMPR2":  "BMP receptor",
    "FZD1": "Wnt receptor",
    "FZD2": "Wnt receptor",
    "NOTCH1": "Notch signaling",
    "TREM2": "microglial receptor",
    "EGFR": "growth factor receptor",
}


# ---------- state I/O helpers ----------

def _latest_iter() -> int:
    dirs = [d for d in STATE.glob("iter_*")
            if d.is_dir() and d.name.split("_")[1].isdigit()]
    if not dirs: return -1
    return max(int(d.name.split("_")[1]) for d in dirs)


def _read_iter(n: int):
    d = STATE / f"iter_{n:03d}"
    plan = json.loads((d / "plan.json").read_text())
    result = json.loads((d / "result.json").read_text())
    issues = json.loads((d / "issues.json").read_text())
    return plan, result, issues


def _stream_params(plan: dict, name: str) -> dict:
    for s in plan["evidence_streams"]:
        if s["name"] == name:
            return s.get("params", {})
    return {}


# ---------- pattern detection ----------

def _receptor_family(rec: str) -> str | None:
    for prefix, fam in RECEPTOR_FAMILIES.items():
        if rec.startswith(prefix):
            return fam
    return None


def _detect_system_patterns(top_n: list) -> list[str]:
    """Find coherent system-level patterns in the top hits."""
    patterns = []
    top10 = top_n[:10]

    # BBB convergence
    bbb_count = sum(1 for r in top10 if r.get("bbb_top_celltype") in BBB_FACING)
    if bbb_count >= 4:
        patterns.append(f"**Brain endothelium / BBB hub**: {bbb_count} of top 10 receptors "
                        f"have a BBB-facing cell type (EC, PC, VSMC, MG, ASC endfeet) as their "
                        f"strongest dose-response cell type — the BBB acts as the central integrator "
                        f"of multiple plasma-borne aging signals.")

    # Same ligand driving multiple top hits
    ligs = [r.get("best_ligand") for r in top10 if r.get("best_ligand")]
    common = Counter(ligs).most_common()
    for lig, n in common:
        if n >= 2:
            recs_for_lig = [r["receptor"] for r in top10 if r.get("best_ligand") == lig]
            patterns.append(f"**{lig} axis convergence**: {n} top-10 receptors "
                            f"({', '.join(recs_for_lig)}) all driven by plasma {lig} — "
                            f"a single ligand changing in plasma is hitting multiple receptors.")

    # Receptor family clusters
    fams = Counter()
    fam_recs = {}
    for r in top10:
        f = _receptor_family(r["receptor"])
        if f:
            fams[f] += 1
            fam_recs.setdefault(f, []).append(r["receptor"])
    for fam, n in fams.most_common():
        if n >= 2:
            patterns.append(f"**{fam}**: {n} members co-occur in top 10 "
                            f"({', '.join(fam_recs[fam])}) — system-level signal, not a single hit.")

    return patterns


def _detect_positive_controls(top_n: list, total_n: int) -> tuple[list, list]:
    """Return (controls in top 25%, controls in eligible universe but lower-ranked)."""
    ranks = {r["receptor"]: r.get("rank", 999) for r in top_n}
    cutoff = max(int(total_n * 0.25), 5)
    in_top = [(r, ranks[r], POSITIVE_CONTROLS[r]) for r in POSITIVE_CONTROLS if r in ranks and ranks[r] <= cutoff]
    in_universe = [(r, ranks[r], POSITIVE_CONTROLS[r]) for r in POSITIVE_CONTROLS if r in ranks and ranks[r] > cutoff]
    return in_top, in_universe


# ---------- PLAN.md ----------

SOURCE_ORDER = [  # logical reading order, not alphabetical
    "lehallier_st4", "lehallier_st14", "lehallier_st1",
    "ximerakis_cellchat", "ximerakis_tpms",
    "jeffries_s7",
    "palovics",
    "omnipath",
]

def _render_plan_md(plan: dict, result: dict) -> str:
    src_used = [k for k in SOURCE_ORDER if k in plan["data_sources"]]
    src_used += [k for k in plan["data_sources"] if k not in SOURCE_ORDER]
    plasma_p = _stream_params(plan, "plasma")
    excl = plasma_p.get("exclude_ligands", [])
    n_excl = len(excl)
    q_thr = plasma_p.get("q_threshold", 0.05)
    w7_w = plasma_p.get("wave7_weight", 1.5)
    brain_p = _stream_params(plan, "brain_doseresp")
    min_rho = brain_p.get("min_rho", 0.7)
    comb = plan["combination"]["method"]
    top1 = result["top_n"][0] if result.get("top_n") else None

    lines = [AUTO_HEADER]
    lines.append("# Plan\n")

    # ---- TOP: question + current answer ----
    lines.append("\n**Goal** — identify the receptor most likely to mediate brain rejuvenation "
                 "through blood-borne factors.\n")
    if top1:
        ep = top1.get("empirical_p")
        ep_str = f", empirical p = {ep:.3f}" if ep is not None else ""
        lines.append(f"\n**Current best answer** — **{top1['receptor']}** "
                     f"(rank 1, score {top1.get('final_score', 0):.2f}{ep_str}). "
                     f"See `RESULTS.md` for the full evidence card.\n")

    # ---- Approach (compact) ----
    lines.append("\n## Approach\n\n")
    lines.append("Receptor-down, not ligand-up: filter to brain-expressed parabiosis-responsive "
                 "receptors first, then layer plasma ligand evidence. Five evidence gates:\n\n")
    lines.append(
        "1. **Brain expression** — must be in Ximerakis CellChat condition-dependent set\n"
        f"2. **Dose-response** — Spearman ρ vs. blood-age axis (YY→OO); |ρ| > {min_rho}\n"
        f"3. **Plasma ligand** — ≥ 1 OmniPath ligand at q.Age < {q_thr}; wave-7 weighted {w7_w}×\n"
        "4. **Directional consistency** — agonist/antagonist sign coherence\n"
        "5. **Cross-species** — sign-concordant in matched human PFC cell type (Jeffries)\n"
        f"\nCombined via **{comb}**.\n"
    )
    if n_excl > 0:
        lines.append(f"\n**Filters applied**: {n_excl} ligands excluded as ECM or SomaScan-questionable "
                     f"(see `pipeline/knowledge/`).\n")

    # ---- DIVIDER ----
    lines.append("\n---\n")
    lines.append("\n*Detail below — read above for the answer.*\n")

    # ---- Detail: hypothesis ----
    lines.append("\n## Hypothesis (full)\n\n")
    lines.append(
        "A receptor is *critical for brain aging* iff all five hold:\n\n"
        "- **(A) Brain expression** on a blood-contacting cell type (endothelium, pericyte, "
        "microglia, astrocyte endfoot, choroid plexus) — hard prerequisite\n"
        "- **(B) Brain signaling responds to blood age** under heterochronic parabiosis\n"
        "- **(C) Cognate plasma ligand changes with age**, large enough to plausibly drive (B)\n"
        "- **(D) Directional consistency** — ligand and receptor changes combine coherently "
        "(agonist↑ + receptor↑/compensatory↓; antagonist↑ + downstream signaling↓)\n"
        "- **(E) Cross-species replication** — same direction in human PFC matched cell type\n"
    )

    # ---- Detail: data sources ----
    lines.append("\n## Data sources\n\n")
    lines.append("| Source | Role |\n|---|---|\n")
    for key in src_used:
        if key in SOURCE_DESCRIPTIONS:
            name, why = SOURCE_DESCRIPTIONS[key]
            lines.append(f"| {name} | {why} |\n")

    return "".join(lines)


# ---------- RESULTS.md ----------

def _render_results_md(plan: dict, result: dict, issues: list) -> str:
    top_n = result["top_n"]
    n_total = result["n_candidates"]
    plasma_p = _stream_params(plan, "plasma")
    n_excl = len(plasma_p.get("exclude_ligands", []))

    lines = [AUTO_HEADER]
    lines.append("# Results\n")

    if not top_n:
        lines.append("\n*Pipeline has not produced any candidates yet.*\n")
        return "".join(lines)

    top1 = top_n[0]

    # ============================================================
    # ABOVE THE FOLD — the answer
    # ============================================================

    # ---- TL;DR (one-liner) ----
    score = top1.get("final_score", 0)
    ep = top1.get("empirical_p")
    ep_str = f", empirical p = {ep:.3f}" if ep is not None else ""
    bbb_ct = top1.get("bbb_top_celltype")
    bbb_rho = top1.get("bbb_top_rho", 0)
    best_lig = top1.get("best_ligand", "—")
    best_q = top1.get("best_q", 0)
    hs_ct = top1.get("hs_top_celltype")
    hs_lfc = top1.get("hs_top_log2FC", 0)

    tldr_bits = [f"**{top1['receptor']}** (score {score:.2f}{ep_str})"]
    if best_lig and best_lig != "—":
        tldr_bits.append(f"driven by plasma **{best_lig}** (q = {best_q:.1e})")
    if bbb_ct and bbb_rho:
        tldr_bits.append(f"strongest brain dose-response in **{bbb_ct}** (ρ = {bbb_rho:+.2f})")
    if hs_ct and hs_lfc:
        tldr_bits.append(f"concordant in human PFC **{hs_ct}** (log2FC = {hs_lfc:+.2f})")

    lines.append(f"\n## Top hit\n\n{'; '.join(tldr_bits)}.\n")

    # ---- Top 5 table ----
    lines.append("\n## Top 5 candidates\n\n")
    lines.append("| rank | receptor | score | best ligand | best q | BBB cell |\n")
    lines.append("|---|---|---|---|---|---|\n")
    for r in top_n[:5]:
        bq = r.get("best_q", 0)
        bq_s = f"{bq:.1e}" if bq else "—"
        ep_v = r.get("empirical_p")
        score_s = f"{r.get('final_score',0):.2f}" + (f" *(p={ep_v:.2f})*" if ep_v is not None else "")
        lines.append(f"| {r.get('rank','?')} | **{r['receptor']}** | {score_s} | "
                     f"{r.get('best_ligand') or '—'} | {bq_s} | "
                     f"{r.get('bbb_top_celltype') or '—'} |\n")

    # ---- System-level patterns (compact, one bullet each) ----
    patterns = _detect_system_patterns(top_n)
    if patterns:
        lines.append("\n## Bigger picture\n\n")
        for p in patterns:
            lines.append(f"- {p}\n")

    # ---- Open questions (only if any) ----
    human_iss = [i for i in issues if not i.get("fix_recipe")]
    if human_iss:
        lines.append(f"\n## What needs human input ({len(human_iss)})\n\n")
        for iss in human_iss:
            q = iss.get("escalation_question") or iss.get("evidence", "")
            lines.append(f"- **{iss['check_name']}** — {q}\n")

    # ---- Recommended next step (compact) ----
    lines.append("\n## Recommended next step\n\n")
    if "palovics" not in plan["data_sources"]:
        lines.append(f"Replicate {top1['receptor']} in Pálovics 2022 brain (Figshare 119145). "
                     f"If direction holds, query GTEx/AMP-AD DLPFC bulk for human replication, "
                     f"then Open Targets for variant-to-brain-age evidence.\n")
    else:
        lines.append(f"Query GTEx/AMP-AD DLPFC bulk RNA-seq for {top1['receptor']} vs. age "
                     f"(bypasses scRNA dropout). Then Open Targets for variant-to-brain-age evidence.\n")

    # ============================================================
    # BELOW THE FOLD — supporting detail
    # ============================================================

    lines.append("\n---\n")
    lines.append("\n*Supporting detail below — read above for the answer.*\n")

    # ---- Top hit evidence card ----
    lines.append(f"\n## Top hit evidence: {top1['receptor']}\n\n")
    lines.append("| Criterion | Evidence |\n|---|---|\n")
    if top1.get("origin"):
        lines.append(f"| CellChat origin | `{top1['origin']}` |\n")
    if bbb_ct:
        lines.append(f"| Brain dose-response | {bbb_ct}: ρ = {bbb_rho:+.2f} vs blood-age axis |\n")
    if best_lig:
        wave = " (7th-decade wave)" if top1.get("best_wave7") else ""
        lines.append(f"| Top plasma ligand | **{best_lig}**{wave}, q = {best_q:.1e} |\n")
    if top1.get("n_sig"):
        all_lig = top1.get('all_sig_ligands', '')
        all_lig_s = all_lig[:80] + ('…' if len(all_lig) > 80 else '')
        lines.append(f"| Plasma support | {top1['n_sig']} sig ligands ({all_lig_s}) |\n")
    if top1.get("dir_total"):
        lines.append(f"| Directional consistency | {top1.get('dir_consistency', 0)}/{top1['dir_total']} "
                     f"agonist/antagonist signs coherent |\n")
    if hs_ct:
        lines.append(f"| Cross-species (human PFC) | {hs_ct}: log2(elderly/adult) = {hs_lfc:+.2f} |\n")

    # ---- Sanity checks (compact) ----
    in_top, in_universe = _detect_positive_controls(top_n, n_total)
    if in_top or in_universe:
        lines.append("\n## Sanity checks\n\n")
        if in_top:
            in_top_str = ", ".join(f"{r} (rank {rank})" for r, rank, _ in sorted(in_top, key=lambda x: x[1]))
            lines.append(f"Positive controls in top quartile: **{in_top_str}**.\n")
        if in_universe:
            other_str = ", ".join(f"{r} (rank {rank})"
                                  for r, rank, _ in sorted(in_universe, key=lambda x: x[1])[:5])
            lines.append(f"Other positive controls present at lower ranks: {other_str}.\n")

    # ---- Method summary (one paragraph) ----
    lines.append("\n## Method (one paragraph)\n\n")
    lines.append(
        f"Receptor universe = {n_total} brain-expressed parabiosis-responsive receptors from "
        f"Ximerakis CellChat. Each scored on (1) brain dose-response (Spearman ρ vs. blood-age), "
        f"(2) plasma ligand strength (Lehallier ST4 q.Age, wave-7-weighted), "
        f"(3) directional consistency (OmniPath agonist/antagonist), "
        f"(4) cross-species concordance (Jeffries human PFC). Combined via Stouffer's Z. "
        f"{n_excl} ligands filtered as ECM or SomaScan-questionable. Full method in `PLAN.md`.\n"
    )

    # ---- Limitations (compact bullets) ----
    lines.append("\n## Limitations\n\n")
    lines.append("- scRNA-seq under-detects low-copy GPCRs (CCR3, GHR, IGF1R absent from universe by construction)\n")
    lines.append("- OmniPath directional annotations missing for many ligands; consistency computed on annotated subset only\n")
    lines.append("- Mouse↔human cell-type mapping is approximate (mouse EC ≈ human endo, etc.)\n")
    lines.append("- SomaScan affinity-reagent caveats; most documented offenders filtered out\n")
    if "palovics" not in plan["data_sources"]:
        lines.append("- No independent mouse parabiosis replication yet (Pálovics not loaded)\n")

    lines.append(f"\n---\n\n")
    lines.append(f"*Full ranked table: `state/iter_{result['iteration']:03d}/master.tsv` "
                 f"({n_total} receptors). History: `python -m pipeline.inspect`.*\n")

    return "".join(lines)


# ---------- entry points ----------

def regenerate_plan_md() -> None:
    latest = _latest_iter()
    if latest < 0:
        PLAN_MD.write_text(AUTO_HEADER + "# Plan\n\n*Pipeline has not been run yet. "
                           "Run `python -m pipeline.loop --fresh` to start.*\n")
        return
    plan, result, _ = _read_iter(latest)
    PLAN_MD.write_text(_render_plan_md(plan, result))


def regenerate_results_md() -> None:
    latest = _latest_iter()
    if latest < 0:
        RESULTS_MD.write_text(AUTO_HEADER + "# Results\n\n*Pipeline has not been run yet.*\n")
        return
    plan, result, issues = _read_iter(latest)
    RESULTS_MD.write_text(_render_results_md(plan, result, issues))


def regenerate_all() -> None:
    regenerate_plan_md()
    regenerate_results_md()
