"""Auto-generate PLAN.md (problem + data + method) and RESULTS.md (findings).

Both documents are regenerated after every loop run from the latest iteration's
state. They are written as final-product narrative documents — they describe
the current best understanding, not the iteration trail. Iteration-by-iteration
details live in `state/iter_log.jsonl` and `state/iter_NNN/`.

Do not hand-edit PLAN.md or RESULTS.md — your edits will be overwritten on
the next loop run. To preserve a hand-written version, save under a different
filename.
"""

from __future__ import annotations
import json
from pathlib import Path
from collections import Counter
from .core import STATE

ROOT = Path(__file__).resolve().parents[1]
PLAN_MD = ROOT / "PLAN.md"
RESULTS_MD = ROOT / "RESULTS.md"

AUTO_HEADER = (
    "<!-- Auto-generated by `python -m pipeline.loop`. Reflects the current "
    "best analysis. Do not hand-edit; regenerated each loop run. -->\n\n"
)

# Domain-knowledge metadata used to describe sources in human terms
SOURCE_DESCRIPTIONS = {
    "ximerakis_cellchat": ("Ximerakis 2023 *Nat Aging* Suppl. Table 20",
                           "CellChat ligand–receptor pairs active in each of the 6 parabiosis "
                           "conditions (YY/YX/OY/YO/OX/OO); we use it to define the receptor "
                           "universe — only receptors whose signaling is condition-dependent qualify"),
    "ximerakis_tpms":     ("Ximerakis 2023 *Nat Aging* Suppl. Table 6",
                           "Per-cell-type TPMs for all 6 parabiosis conditions; lets us compute "
                           "Spearman dose-response of each receptor against the blood-age axis"),
    "lehallier_st1":      ("Lehallier 2019 *Nat Med* Suppl. Table 1",
                           "Maps SomaScan reagent IDs to gene symbols — required to join plasma "
                           "data to the OmniPath ligand–receptor catalog"),
    "lehallier_st4":      ("Lehallier 2019 *Nat Med* Suppl. Table 4",
                           "Per-protein age coefficient + q-value across n=4,263 humans (18–95y); "
                           "the primary plasma age signal"),
    "lehallier_st14":     ("Lehallier 2019 *Nat Med* Suppl. Table 14",
                           "DE-SWAN three-decade structure (4th, 7th, 8th decade waves); we "
                           "weight 7th-decade ligands more heavily because that window aligns "
                           "with onset of cognitive decline"),
    "jeffries_s7":        ("Jeffries 2025 *Nature* Suppl. Table 7",
                           "Per-cell-type continuous age slope in human PFC across the full "
                           "lifespan; used to test cross-species replication"),
    "omnipath":           ("OmniPath ligand–receptor catalog",
                           "Curated union of CellPhoneDB, CellTalkDB, Cellinker, Baccin2019, "
                           "Guide2Pharma, Ramilowski2015, etc. — provides ligand↔receptor edges "
                           "and agonist/antagonist annotations"),
    "palovics":           ("Pálovics 2022 *Nature* brain subset (Figshare 119145)",
                           "Independent mouse parabiosis cohort, used only to replicate the "
                           "short list once a top hit emerges"),
}

BBB_FACING = {"EC", "PC", "VSMC", "MG", "MNC", "DC", "ABC", "VLMC", "CPC"}

# Known receptor families for system-level pattern detection
RECEPTOR_FAMILIES = {
    "FZD":  "Wnt/Frizzled receptor family",
    "BMPR": "BMP receptor family",
    "ACVR": "Activin/BMP receptor family",
    "TGFBR": "TGF-β receptor family",
    "FGFR": "FGF receptor family",
    "IGF":  "Insulin-like growth factor receptor",
    "VEGFR": "VEGF receptor family",
    "FLT":  "VEGF receptor family",  # FLT1 = VEGFR1
    "KDR":  "VEGF receptor family",  # KDR = VEGFR2
    "NRP":  "Neuropilin (VEGF co-receptor) family",
    "CXCR": "CXC chemokine receptor family",
    "CCR":  "CC chemokine receptor family",
    "ITGA": "Integrin alpha family",
    "ITGB": "Integrin beta family",
    "TLR":  "Toll-like receptor family",
    "TNFRSF": "TNF receptor superfamily",
    "NOTCH": "Notch receptor family",
    "ADGR": "Adhesion GPCR family",
    "LRP":  "LDL receptor-related protein family (Wnt co-receptor)",
}

POSITIVE_CONTROLS = {  # known brain-aging-relevant receptors for sanity check
    "LRP6": "Wnt co-receptor; SOST/DKK1 axis",
    "CD44": "hyaluronan receptor; senescence marker",
    "CXCR4": "SDF-1 receptor; neurogenesis",
    "C3AR1": "complement receptor; neuroinflammation",
    "C5AR1": "complement receptor; neuroinflammation",
    "IL6ST": "gp130; IL-6 family neuroinflammation",
    "TGFBR1": "TGF-β receptor",
    "TGFBR2": "TGF-β receptor",
    "BMPR1A": "BMP receptor; GDF11 axis",
    "BMPR2":  "BMP receptor",
    "FZD1": "Wnt receptor",
    "FZD2": "Wnt receptor",
    "NOTCH1": "Notch signaling",
    "TREM2": "microglial receptor",
    "EGFR": "growth factor receptor",
}


# ---------- state I/O helpers ----------

def _latest_iter() -> int:
    dirs = [d for d in STATE.glob("iter_*")
            if d.is_dir() and d.name.split("_")[1].isdigit()]
    if not dirs: return -1
    return max(int(d.name.split("_")[1]) for d in dirs)


def _read_iter(n: int):
    d = STATE / f"iter_{n:03d}"
    plan = json.loads((d / "plan.json").read_text())
    result = json.loads((d / "result.json").read_text())
    issues = json.loads((d / "issues.json").read_text())
    return plan, result, issues


def _stream_params(plan: dict, name: str) -> dict:
    for s in plan["evidence_streams"]:
        if s["name"] == name:
            return s.get("params", {})
    return {}


# ---------- pattern detection ----------

def _receptor_family(rec: str) -> str | None:
    for prefix, fam in RECEPTOR_FAMILIES.items():
        if rec.startswith(prefix):
            return fam
    return None


def _detect_system_patterns(top_n: list) -> list[str]:
    """Find coherent system-level patterns in the top hits."""
    patterns = []
    top10 = top_n[:10]

    # BBB convergence
    bbb_count = sum(1 for r in top10 if r.get("bbb_top_celltype") in BBB_FACING)
    if bbb_count >= 4:
        patterns.append(f"**Brain endothelium / BBB hub**: {bbb_count} of top 10 receptors "
                        f"have a BBB-facing cell type (EC, PC, VSMC, MG, ASC endfeet) as their "
                        f"strongest dose-response cell type — the BBB acts as the central integrator "
                        f"of multiple plasma-borne aging signals.")

    # Same ligand driving multiple top hits
    ligs = [r.get("best_ligand") for r in top10 if r.get("best_ligand")]
    common = Counter(ligs).most_common()
    for lig, n in common:
        if n >= 2:
            recs_for_lig = [r["receptor"] for r in top10 if r.get("best_ligand") == lig]
            patterns.append(f"**{lig} axis convergence**: {n} top-10 receptors "
                            f"({', '.join(recs_for_lig)}) all driven by plasma {lig} — "
                            f"a single ligand changing in plasma is hitting multiple receptors.")

    # Receptor family clusters
    fams = Counter()
    fam_recs = {}
    for r in top10:
        f = _receptor_family(r["receptor"])
        if f:
            fams[f] += 1
            fam_recs.setdefault(f, []).append(r["receptor"])
    for fam, n in fams.most_common():
        if n >= 2:
            patterns.append(f"**{fam}**: {n} members co-occur in top 10 "
                            f"({', '.join(fam_recs[fam])}) — system-level signal, not a single hit.")

    return patterns


def _detect_positive_controls(top_n: list, total_n: int) -> tuple[list, list]:
    """Return (controls in top 25%, controls in eligible universe but lower-ranked)."""
    ranks = {r["receptor"]: r.get("rank", 999) for r in top_n}
    cutoff = max(int(total_n * 0.25), 5)
    in_top = [(r, ranks[r], POSITIVE_CONTROLS[r]) for r in POSITIVE_CONTROLS if r in ranks and ranks[r] <= cutoff]
    in_universe = [(r, ranks[r], POSITIVE_CONTROLS[r]) for r in POSITIVE_CONTROLS if r in ranks and ranks[r] > cutoff]
    return in_top, in_universe


# ---------- PLAN.md ----------

SOURCE_ORDER = [  # logical reading order, not alphabetical
    "lehallier_st4", "lehallier_st14", "lehallier_st1",
    "ximerakis_cellchat", "ximerakis_tpms",
    "jeffries_s7",
    "palovics",
    "omnipath",
]

def _render_plan_md(plan: dict, result: dict) -> str:
    src_used = [k for k in SOURCE_ORDER if k in plan["data_sources"]]
    src_used += [k for k in plan["data_sources"] if k not in SOURCE_ORDER]
    plasma_p = _stream_params(plan, "plasma")
    excl = plasma_p.get("exclude_ligands", [])
    n_excl = len(excl)
    q_thr = plasma_p.get("q_threshold", 0.05)
    w7_w = plasma_p.get("wave7_weight", 1.5)
    brain_p = _stream_params(plan, "brain_doseresp")
    min_rho = brain_p.get("min_rho", 0.7)
    comb = plan["combination"]["method"]

    lines = [AUTO_HEADER]
    lines.append("# Plan: Discovering the Most Critical Receptor for Brain Rejuvenation\n")

    lines.append("\n## The question\n\n")
    lines.append(
        "We want to identify the receptor (or receptor system) most likely to causally mediate "
        "the effect of blood-borne factors on brain aging. The biological logic: as people age, "
        "plasma composition changes; for these blood signals to affect brain function, they must "
        "act through a receptor on a brain cell. Identifying that receptor pinpoints the most "
        "actionable intervention target — including for therapeutic repurposing.\n"
    )

    lines.append("\n## Data resources\n\n")
    lines.append("| Source | Role |\n|---|---|\n")
    for key in src_used:
        if key in SOURCE_DESCRIPTIONS:
            name, why = SOURCE_DESCRIPTIONS[key]
            lines.append(f"| {name} | {why} |\n")

    lines.append("\n## Core hypothesis\n\n")
    lines.append(
        "A receptor is *critical for brain aging* if and only if all five conditions hold:\n\n"
        "- **(A) Brain expression** — expressed on a brain cell type that contacts blood "
        "(endothelium, pericyte, microglia, astrocyte endfoot, choroid plexus). "
        "**Hard prerequisite, not a score.**\n"
        "- **(B) Brain signaling responds to blood age** — receptor expression and/or its "
        "inferred ligand–receptor activity shifts under heterochronic parabiosis (old getting "
        "young blood, young getting old blood).\n"
        "- **(C) Cognate ligand changes in plasma with age** — the ligand side of the receptor's "
        "signaling axis changes in human plasma with age, large enough to plausibly drive (B).\n"
        "- **(D) Directional consistency** — ligand and receptor changes combine coherently "
        "(an agonist that rises in plasma should pair with receptor up- or compensatory "
        "down-regulation; an antagonist that rises should pair with reduced downstream signaling).\n"
        "- **(E) Cross-species replication** — the human PFC shows the same age-direction in "
        "the matched cell type as the mouse brain.\n"
    )

    lines.append("\n## Method — receptor-down, not ligand-up\n\n")
    lines.append(
        "The pipeline starts from the **brain-side** filter (receptors that CellChat already "
        "validated as brain-expressed and parabiosis-responsive) and only then asks whether "
        "plasma ligand evidence fits. This reverses the naive ligand-up approach, which would "
        "pull in many receptors with no real brain expression.\n\n"
        "Each candidate receptor must pass five gates:\n\n"
    )
    lines.append("| Gate | Criterion | Implementation |\n|---|---|---|\n")
    lines.append("| A | Brain expression + parabiosis-responsive | "
                 "In Ximerakis CellChat S20 condition-dependent set (RJV-restored ∪ aging-gained "
                 "∪ aging-lost ∪ AGA-induced) |\n")
    lines.append(f"| B | Blood-age dose-response in brain | "
                 f"Spearman ρ between receptor TPM and the blood-age ordinal axis "
                 f"(YY=0, YX=1, OY=2, YO=3, OX=4, OO=5) per cell type; |ρ| > {min_rho} required |\n")
    lines.append(f"| C | Plasma ligand changes with age | "
                 f"At least one OmniPath ligand with q.Age < {q_thr} in Lehallier ST4. "
                 f"7th-decade-wave ligands (cognitive-decline window) get {w7_w}× weight |\n")
    lines.append("| D | Directional consistency | OmniPath agonist/antagonist annotations check "
                 "whether ligand-side and receptor-side changes are sign-coherent |\n")
    lines.append("| E | Cross-species replication | Sign-concordant change in matched human PFC "
                 "cell type (Jeffries S7), with mouse↔human cell type mapping |\n")

    lines.append(f"\nThe four evidence dimensions (B–E) are converted to z-scores by ranking and "
                 f"combined via **{comb}**.\n")

    if n_excl > 0:
        lines.append(f"\n**Currently excluded from the plasma ligand pool**: {n_excl} ligands "
                     f"are filtered out as either ECM proteins (not credibly blood-borne) or "
                     f"SomaScan reagents with documented crossreactivity issues. The exclusion "
                     f"list is in `pipeline/knowledge/`.\n")

    lines.append("\n## Outputs\n\n")
    lines.append("- **`RESULTS.md`** — narrative findings (also auto-generated)\n")
    lines.append("- **`state/iter_NNN/master.tsv`** — full ranked candidates with all evidence columns\n")
    lines.append("- **`state/iter_log.jsonl`** — pipeline run history (one JSON line per iteration)\n")
    lines.append("- **`state/escalations.md`** — open questions for human review\n")
    lines.append("- **`pipeline/USAGE.md`** — how to run, inspect, and extend the pipeline\n")

    return "".join(lines)


# ---------- RESULTS.md ----------

def _render_results_md(plan: dict, result: dict, issues: list) -> str:
    top_n = result["top_n"]
    n_total = result["n_candidates"]
    plasma_p = _stream_params(plan, "plasma")
    n_excl = len(plasma_p.get("exclude_ligands", []))

    lines = [AUTO_HEADER]
    lines.append("# Results: Most Critical Receptor for Brain Rejuvenation\n")

    # ---- I. The question ----
    lines.append("\n## I. The biological question\n\n")
    lines.append(
        "Which receptor (or receptor system) most likely mediates the effect of blood-borne "
        "factors on brain aging? Heterochronic parabiosis (Wyss-Coray and others) shows that "
        "young blood rejuvenates aged brain and old blood prematurely ages young brain — "
        "establishing that **plasma carries causally relevant signals**. What remains unknown "
        "is which receptors on which brain cells transduce those signals.\n"
    )

    # ---- II. Why these papers ----
    lines.append("\n## II. The causal chain we trace\n\n")
    lines.append("```\nplasma ligand ──(Lehallier 2019)──> crosses BBB ──> brain receptor "
                 "──(Ximerakis 2023)──> downstream effects\n"
                 "                                                  │\n"
                 "                                       (Jeffries 2025: human-brain validation)\n"
                 "                                                  │\n"
                 "                                       (Pálovics 2022: mouse replication)\n```\n")
    lines.append("Each paper covers one segment; none alone is sufficient.\n")

    # ---- III. Method (brief) ----
    lines.append("\n## III. Method (summary)\n\n")
    lines.append(
        f"The receptor universe is the {n_total} brain-expressed, parabiosis-responsive "
        f"receptors from Ximerakis CellChat. Each receptor accumulates evidence on four "
        f"dimensions (brain dose-response, plasma ligand strength, directional consistency, "
        f"cross-species replication) which are combined via Stouffer's Z. "
        f"{n_excl} ligands are filtered as ECM or methodologically unreliable (SomaScan "
        f"crossreactive). Detail in `PLAN.md`.\n"
    )

    # ---- IV. Findings ----
    lines.append("\n## IV. Findings\n")
    if not top_n:
        lines.append("\n*No candidates produced — pipeline not yet run.*\n")
    else:
        top1 = top_n[0]
        lines.append(f"\n### Top single receptor: **{top1['receptor']}**\n\n")
        score = top1.get("final_score", 0)
        ep = top1.get("empirical_p")
        lines.append(f"Final score **{score:.2f}**" +
                     (f" (empirical p = {ep:.3f} vs. 1,000-permutation null)" if ep is not None else "") +
                     ".\n\n")
        lines.append("| Criterion | Evidence |\n|---|---|\n")
        if top1.get("origin"):
            lines.append(f"| CellChat origin | `{top1['origin']}` |\n")
        bbb_ct = top1.get("bbb_top_celltype")
        bbb_rho = top1.get("bbb_top_rho", 0)
        if bbb_ct:
            lines.append(f"| Brain dose-response | {bbb_ct} (BBB-facing): ρ = {bbb_rho:+.2f} vs blood-age axis |\n")
        if top1.get("best_ligand"):
            wave = " (7th-decade wave)" if top1.get("best_wave7") else ""
            lines.append(f"| Top plasma ligand | **{top1['best_ligand']}**{wave}, q = {top1.get('best_q', 0):.1e} |\n")
        if top1.get("n_sig"):
            lines.append(f"| Plasma support | {top1['n_sig']} ligands at q < 0.05 "
                         f"({top1.get('all_sig_ligands', '')[:80]}{'…' if len(top1.get('all_sig_ligands','')) > 80 else ''}) |\n")
        if top1.get("dir_total"):
            lines.append(f"| Directional consistency | {top1.get('dir_consistency', 0)}/{top1['dir_total']} "
                         f"agonist/antagonist ligands sign-coherent |\n")
        if top1.get("hs_top_celltype"):
            lines.append(f"| Cross-species (human PFC) | {top1['hs_top_celltype']}: "
                         f"log2(elderly/adult) = {top1.get('hs_top_log2FC', 0):+.2f} |\n")

        # ---- Runner-ups ----
        if len(top_n) > 1:
            lines.append("\n### Runner-up tier (rank 2–5)\n\n")
            lines.append("| Rank | Receptor | Score | Best ligand | BBB cell type | Origin |\n")
            lines.append("|---|---|---|---|---|---|\n")
            for r in top_n[1:5]:
                ep_s = f" (p={r.get('empirical_p'):.2f})" if r.get("empirical_p") is not None else ""
                lines.append(f"| {r.get('rank','?')} | **{r['receptor']}** | "
                             f"{r.get('final_score',0):.2f}{ep_s} | "
                             f"{r.get('best_ligand') or '—'} | "
                             f"{r.get('bbb_top_celltype') or '—'} | "
                             f"{r.get('origin','')} |\n")

        # ---- System-level patterns ----
        patterns = _detect_system_patterns(top_n)
        if patterns:
            lines.append("\n### System-level patterns\n\n")
            for p in patterns:
                lines.append(f"- {p}\n")

    # ---- V. Sanity checks ----
    if top_n:
        lines.append("\n## V. Sanity checks\n\n")
        in_top, in_universe = _detect_positive_controls(top_n, n_total)
        if in_top:
            lines.append(f"**Positive controls found in top quartile** (expected if scoring is biologically sensible):\n\n")
            for r, rank, note in sorted(in_top, key=lambda x: x[1]):
                lines.append(f"- **{r}** (rank {rank}) — {note}\n")
        if in_universe:
            lines.append(f"\n**Other positive controls in the eligible set** (lower-ranked, "
                         f"expected if their evidence is genuinely weaker):\n\n")
            for r, rank, note in sorted(in_universe, key=lambda x: x[1])[:5]:
                lines.append(f"- {r} (rank {rank}) — {note}\n")

    # ---- VI. Open questions / limitations ----
    human_iss = [i for i in issues if not i.get("fix_recipe")]
    if human_iss:
        lines.append(f"\n## VI. Open questions for human review\n\n")
        for i, iss in enumerate(human_iss, 1):
            lines.append(f"**{i}. {iss['check_name']}** — {iss['evidence']}\n")
            if iss.get("escalation_question"):
                lines.append(f"\n   → *{iss['escalation_question']}*\n\n")

    # ---- VII. Standing limitations ----
    lines.append("\n## VII. Standing limitations\n\n")
    lines.append("1. **scRNA-seq under-detects low-abundance receptors** (especially GPCRs). "
                 "CCR3, GHR, IGF1R and other known aging-relevant low-copy receptors are "
                 "absent from the CellChat universe and therefore from this analysis.\n")
    lines.append("2. **OmniPath directional annotations are missing for many ligands** — "
                 "directional consistency is computed only over the annotated subset.\n")
    lines.append("3. **Mouse↔human cell-type mapping is approximate** — mouse EC ≈ human "
                 "endo, mouse MG ≈ human micro, etc., but cells are not strictly equivalent.\n")
    lines.append("4. **Plasma proteomic data is SomaScan-based** — affinity-reagent specificity "
                 "caveats apply; the most documented offenders are filtered out via "
                 "`pipeline/knowledge/somascan_questionable.tsv`.\n")
    if "palovics" not in plan["data_sources"]:
        lines.append("5. **No independent mouse parabiosis replication yet** (Pálovics 2022 brain "
                     "subset not loaded). Top hits depend on a single mouse cohort (Ximerakis).\n")

    # ---- VIII. Next steps ----
    lines.append("\n## VIII. Suggested next steps\n\n")
    lines.append("1. **Independent mouse replication**: load Pálovics 2022 brain subset and "
                 "verify the top 5 dose-response.\n")
    lines.append("2. **Human bulk replication**: query GTEx and AMP-AD (ROSMAP) for the top "
                 "candidates' expression vs. chronological age in DLPFC — bypasses scRNA-seq's "
                 "detection floor for low-copy receptors.\n")
    lines.append("3. **Human genetics**: query Open Targets / GWAS Catalog for variants in the "
                 "top candidates associated with brain-aging traits (UK Biobank brain age, "
                 "Alzheimer's, cognitive trajectories).\n")
    if top_n:
        top1_rec = top_n[0]["receptor"]
        lines.append(f"4. **If {top1_rec} replicates**: propose a heterochronic parabiosis × "
                     f"brain-endothelium-specific {top1_rec} conditional knockout to test whether "
                     f"removing it from the BBB abolishes the rejuvenation effect of young blood.\n")

    lines.append(f"\n---\n\n")
    lines.append(f"*Full ranked table at `state/iter_{result['iteration']:03d}/master.tsv` "
                 f"({n_total} receptors). Pipeline run history: `python -m pipeline.inspect`.*\n")

    return "".join(lines)


# ---------- entry points ----------

def regenerate_plan_md() -> None:
    latest = _latest_iter()
    if latest < 0:
        PLAN_MD.write_text(AUTO_HEADER + "# Plan\n\n*Pipeline has not been run yet. "
                           "Run `python -m pipeline.loop --fresh` to start.*\n")
        return
    plan, result, _ = _read_iter(latest)
    PLAN_MD.write_text(_render_plan_md(plan, result))


def regenerate_results_md() -> None:
    latest = _latest_iter()
    if latest < 0:
        RESULTS_MD.write_text(AUTO_HEADER + "# Results\n\n*Pipeline has not been run yet.*\n")
        return
    plan, result, issues = _read_iter(latest)
    RESULTS_MD.write_text(_render_results_md(plan, result, issues))


def regenerate_all() -> None:
    regenerate_plan_md()
    regenerate_results_md()
